### ISSUE TITLE
日本語訳の揺れ

### ISSUE THREAD

**Issue by kenjis** [NEKOGET/FuelPHP_docs_jp#13]
日本語訳に表記の揺れがみられますね。

以下の Wiki にまとめることにしました。
https://github.com/NEKOGET/FuelPHP_docs_jp/wiki/%E6%97%A5%E6%9C%AC%E8%AA%9E%E8%A8%B3%E3%81%AE%E6%8F%BA%E3%82%8C

はやめに統一していったほうがいいと思います。

**Comment by kenjis** [comment]
英単語の前後のスペースは、現在の PC のブラウザで見るかぎり、入れた方が見やすいですね。
ないとつまりすぎる感じがします。

**Comment by ounziw** [comment]
独自にルール決めするのはコストがかかるので、既存のものに乗っかりましょう。

例えば、サン・マイクロシステムズの斎藤さんのスタイルガイド
http://blogs.oracle.com/reiko/resource/ja-style-quick.pdf

**Comment by kenjis** [comment]
これですが、
http://blogs.oracle.com/reiko/resource/ja-style-quick.pdf
を全部摘要するということでしょうか？

ちなみに、ここで議論しても翻訳者のほとんどの人は見てない可能性あるわけですよね？
書き込みしない限り、メールが飛ぶわけでもないですし。

**Comment by ounziw** [comment]
http://blogs.oracle.com/reiko/resource/ja-style-quick.pdf
ある程度纏まっているものの例なので、他のものでも構いません。
php の他のフレームワークに準拠する、みたいな方法もありだと思います。

> ちなみに、ここで議論しても翻訳者のほとんどの人は見てない可能性あるわけですよね？

公式サイトを早めに整備する必要がありますね。

**Comment by kenjis** [comment]
いえ、これ全部に準拠するのは結構大変なんじゃないかなと。

議論の場については、Googleグループができましたので、そこでいいかと思います。
https://groups.google.com/group/fuelphp_jp?hl=ja

**Comment by ounziw** [comment]
じゃあ、もっとシンプルなものを探すか、
http://blogs.oracle.com/reiko/resource/ja-style-quick.pdf の一部のみを抽出するか、ですね。
