### ISSUE TITLE
oil:Generateページの乱れ

### ISSUE THREAD

**Issue by HiroKws** [NEKOGET/FuelPHP_docs_jp#31]
お騒がせしております。HiroKwsこと、Hirohisa Kawasaeです。

nekogetさんが公開されているドキュメントのOil：Generateのページの表示が乱れています。

nekogetさんが公開されているドキュメントと、こちらで公開されているドキュメントの内容が全く同じであるか、確認しておりませんが、こちらが一番適当であろうと思いますので、ご報告させて頂きます。

見た目では、Changing Timestamp Fieldsセクションの前後から始まっているようですが、htmlまで調査しておりません。

以上

**Comment by kenjis** [comment]
この Issue、close してもらえませんでしょうか？

**Comment by NEKOGET** [comment]
はーい
