### ISSUE TITLE
「FuelPHP Documentation 日本語版執筆基準」での《いわゆる 2 バイト文字》という表現

### ISSUE THREAD

**Issue by iwaim** [NEKOGET/FuelPHP_docs_jp#475]
《日本語には全角文字 (いわゆる 2 バイト文字) を使う。》でいわんとしていることは理解できるのですが、UTF-8が普通な時代で育った人は混乱しちゃいそうな気がしています。別のところでは「UTF-8使え」とあるので。

「いわゆる」という表現があるから大丈夫という見解もありそうですが、ここからは括弧部分を除去するか、「(マルチバイト文字)」にしてしまうのはどうでしょうか？

**Comment by kenjis** [comment]
確かにちょっとわかりにくいですね。 2バイトというのも、今となってはまぎらわしいですかね。

これは、全角文字なので、「半角かな」を使わないという意味ですかね。

「マルチバイト文字」だと半角かなも、UTF-8ではマルチバイトですね。単純にカッコ書きを削除でしょうか。

**Comment by iwaim** [comment]
確かにマルチバイトだとダメそうですね。除去がよさそうです。

**Comment by kenjis** [comment]
削除しました。

https://github.com/NEKOGET/FuelPHP_docs_jp/wiki/FuelPHP-Documentation-%E6%97%A5%E6%9C%AC%E8%AA%9E%E7%89%88%E5%9F%B7%E7%AD%86%E5%9F%BA%E6%BA%96/_compare/3bcdc12990567bcd5df3ab86a37f22edd7682103...7d945823222fcd24e8af526fa9946769731c6758

**Comment by iwaim** [comment]
対応ありがとうございます。削除されていることを確認しました。
